# Uncomment this line to define a global platform for your project
# platform :ios, '14.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
 #pod 'ChatSDK', :git => 'https://github.com/zendesk/chat_sdk_ios.git'     
 #pod 'ChatProvidersSDK', :git => 'https://github.com/zendesk/chat_providers_sdk_ios.git'
 #pod 'ZendeskSDKSocketClient', :git => 'https://github.com/zendesk/sdk_socket_client_ios.git'
 #pod 'ZendeskChatSDK', :path => 'file:///Users/dmitrydyachenko/Downloads/zdplugin/ios/chat_sdk_ios-master/ChatSDK.framework'#'2.11.2'
 pod 'ZendeskChatSDK', :git => 'https://github.com/zendesk/chat_sdk_ios.git'
 pod 'ZendeskChatProvidersSDK', :git => 'https://github.com/zendesk/chat_providers_sdk_ios.git' #'2.11.2'
 pod 'ZendeskMessagingSDK', :git => 'https://github.com/zendesk/messaging_sdk_ios.git'
 pod 'ZendeskMessagingAPISDK', :git => 'https://github.com/zendesk/messagingapi_sdk_ios.git'
 pod 'ZendeskCommonUISDK', :git => 'https://github.com/zendesk/commonui_sdk_ios.git'
 pod 'ZendeskSDKConfigurationsSDK', :git => 'https://github.com/zendesk/sdkconfigurations_sdk_ios.git'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
